### ISSUE TITLE
Problem when makes the pok-main example arinc653-queueing

### ISSUE THREAD

**Issue by hwd88** [OpenAADL/AADLib#23]
When runs the command "ocarina -aadlv2 -f -i model.aadl", hit the following problem:
"model.aadl:20:06: ARINC653 (identifier) is not a package or a property set visible or existing
Cannot analyze AADL specifications"

The platform is Ubuntu 20.04.2 LTS (GNU Linux 5.11.0.-27-generic x86_64))
Ocarina v2021.1-7-g563ae64 (Working Copy from r563ae649)
Build date: Oct 29 2021 14:47:37

And advise? Thanks a lot.

Wayne

**Comment by jjhugues** [comment]
Hi,

This is not an AADLib error, so please have it reported to POK maintainers.
You want to run `ocarina -aadlv2  -y -i model.aadl` , i.e. use -y to load files on demand since ARINC653 is not a standard property sets. You will get additional errors related to error handling, this is because this example uses an outdated property set. See OSATE for the reference one, it is likely the corresponding code generation feature is no longer working.

**Comment by hwd88** [comment]
Thanks
